# -*- coding: utf-8 -*-
"""Copy of Patterns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1plrTJbW2F1EX8nL_BzKw2XwUBWPg1NUm
"""

#upper right angled triangle
n=int(input())
for i in range(1,n):
  for j in range(1,n):
    if i<=j:
      print(j,end=" ")
    else:
      print(" ",end=" ")
  print()

#Hallow square n=4
n=int(input())
for i in range(n):
  for j in range(n):
    if i==0 or i==n-1 or j==0 or j==n-1:
      print("*",end=" ")
    else:
      print(" ",end=" ")
  print()

#Hallow triangle
n=int(input())
for i in range(n):
  for j in range(n):
    if j==0 or i==n-1 or i==j:
      print("*",end=" ")
    else:
      print(" ",end=" ")
  print()

#Hallow x-pattern
n=int(input())
for i in range(n):
  for j in range(n):
    if i==j or  i+j==n-1:
      print("* ",end=" ")
    else:
      print(" ",end=" ")
  print()

n=5
for i in range(1,n+1):
  print("* "*i)

n=5
for i in range(n,0,-1):
  print("* "*i)

n=5
for i in range(1,n+1):
  print(" "*(n-i)+"*" *i)

n=6
for i in range(n):
  if i % 2==0:
    for j in range(n):
      print("*",end=" ")
  else:
    for j in range(n):
      print("+",end=" ")
  print()

n=6
for i in range(n):
  if i % 2==0:
    for j in range(n):
      if i>=j:
        print("*",end=" ")
  else:
    for j in range(n):
      if i>=j:
        print("+",end=" ")
  print()

n=8
for i in range(n):
  print(" "*(n-i)+"* " *i)
for  i in range(n,0,-1):
  print(" "*(n-i)+"* " *i)

#Print letter "P"
n=10
for i in range(n):
  for j in range(n):
    if j==0:
      print("*",end=" ")
    elif (i==0 or i==n//2) and j<n-1:
      print("*",end=" ")
    elif i<n//2 and j==n-1:
      print("*",end=" ")
    else:
      print(" ",end=" ")
  print()

#letter -C
n=10
for i in range(n):
  for j in range(n):
    if i==0 and j>1:
      print("* ",end=" ")
    elif j==0 and (i>0 and i<n-1):
      print("* ",end=" ")
    elif i==n-1 and j>1:
      print("* ",end=" ")
    else:
      print("",end=" ")
  print()

